fix Verus errors
the latest version of Verus gave errors like these:

error: disallowed: field expression for a non-visible datatype
   --> kv2/keys/inv_v.rs:212:33
    |
70  | / pub(super) struct KeyMemoryMapping<K> {
71  | |     pub row_info: Map<u64, KeyRowDisposition<K>>,
72  | |     pub key_info: Map<K, u64>,
73  | |     pub item_info: Map<u64, u64>,
74  | |     pub list_info: Map<u64, u64>,
75  | | }
    | |_- this datatype is only visible to `lib::kv2::keys`
...
212 |                   |row_addr: u64| self.row_info.contains_key(row_addr),
    |                                   ^^^^^^^^^^^^^ this field expression is disallowed because of non-visibility
    |
    = help: note that because this is a pub open spec function, this field expression must be well-formed everywhere, which is wider than `lib::kv2::keys`